### ISSUE TITLE
Media Upload issue in app

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/iOS.MySurveysApp#1]
When we try uploading video in app, it keeps saying uploading and nothing happens after that.
Similarly,when we try to access gallery to upload an image, it does work (however, we can click an image and upload). 
This issue happens in both android and iOS.

**Comment by nikul-opg** [comment]
From dot net side we are calling the api and getting the error message while uploading the video

**Comment by dougmorris** [comment]
@nikul-opg please can you share the API being used with full details and the sample media.

**Comment by dougmorris** [comment]
@nikul-opg I have updated the web.config in order to allow for large files. I am reluctant to test on dev with my phone as I have live set up as I want it.

**Comment by dougmorris** [comment]
There was a missing file from the AdminSuite/media folder called qt-faststart.exe
After adding this it started working. This is inplace on staging and in the live server.

**Comment by pavithra-opg** [comment]
@dougmorris Thanks.
 I checked the upload issue in staging build:
@durgajadapolu iOS it keeps giving an alert/pop-up message as shown to you
@nikul-opg when we login and try uploading the media/access the camera button , it throws cordova error. Please note this happens for the very first time.

**Comment by dougmorris** [comment]
@durgajadapolu @nikul-opg I would look to you guys to replicate it.

**Comment by nikul-opg** [comment]
@pavithra-opg android cordova isssue is fixed

**Comment by pavithra-opg** [comment]
@nikul-opg  thank you. I checked and it worked.
@durgajadapolu: I will wait for your update

**Comment by durgajadapolu** [comment]
I had checked this issue and  fixed it, this is because of cordova Initialization is not happen properly for the first time launch.

**Comment by pavithra-opg** [comment]
Hi Guys,
In Deeplinking survey, the upload issue(cordova error) occurs for the very first media upload question.

**Comment by nikul-opg** [comment]
I have checked the issue. It's taking time to load java script of cordova as it is in the bottom of body part. So opgWidgets is not able to find the function of cordova.

**Comment by dougmorris** [comment]
@nikul-opg @durgajadapolu  I am happy to make any necessary adjustments on the server side as required, but need to be lead by you and the UI guys.

**Comment by dougmorris** [comment]
@nikul-opg @durgajadapolu can you confirm what you want changing please. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nikul-opg** [comment]
Can we move this two line from body to in starting of head<script type="text/javascript" src="b1/cordova_android.js"></script>
<script type="text/javascript" src="cordovaFunction.js"></script>

**Comment by dougmorris** [comment]
@nikul-opg This is in place on the DEV platform. Please confirm you are happy with this.

**Comment by nikul-opg** [comment]
@dougmorris  I checked the issue now we are not getting any error related to Cordova . Checked in the dev server

**Comment by dougmorris** [comment]
@nikul-opg so what is the next action?

**Comment by nikul-opg** [comment]
@dougmorris  We'll update this in staging.

**Comment by pavithra-opg** [comment]
Media upload questions(deep linking surveys as well) works
