### ISSUE TITLE
Media upload issue - Without login into application.

### ISSUE THREAD

**Issue by durgajadapolu** [OnePointGlobal/iOS.MySurveysApp#2]
In deep linking surveys media upload is not working without login, but it is working fine with login. This is in live, dev and staging servers. I am getting an error from API request here I mention below.
{
    ErrorMessage = "Object reference not set to an instance of an object.";
    HttpStatusCode = 406;
    Message = "An error has encountered.";
}

Live APi url : https://api.1pt.mobi/V3.1/Api/media/post

**Comment by dougmorris** [comment]
Thanks @durgajadapolu - just waiting for the header and body details you are using so I can replicate the problem.

**Comment by dougmorris** [comment]
@nikul-opg @durgajadapolu after your great testing we found that the request had a data= on the end of the url which appeared to cause the issue and create a badly formed request for the server to process.
