### ISSUE TITLE
Staging (test build V2.1.4): Please change the app name from "MySurveys2.0" to "My Surveys" in all the generic system messages.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/iOS.MySurveysApp#3]
Normally, it comes for all the permission alerts.

**Comment by durgajadapolu** [comment]
It is fixed and available in the next build.
- User end messages like (alerts, error messages, permission messages) which are showing "My Surveys2.0" is changed to "My Surveys". But the project name "MySurveys2.0" reference can not be changed because it will give conflicts in the project.

**Comment by onepointpb** [comment]
It is fixed and available in the App Store.
