### ISSUE TITLE
After taking an offline survey, the status bar is getting disappeared from the header area of the device.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/iOS.MySurveysApp#6]
After this the landing page of the app is showing the module name that was last clicked or visited.

**Comment by onepointpb** [comment]
After investigating we found that this is happening because of the uploaded video preview.

**Comment by durgajadapolu** [comment]
I have checked this issue it is happening with only one of the script remaining all scripts it is working fine.

**Comment by onepointpb** [comment]
Closing this issue as it is working fine with other scripts.
